import {Images} from '../images/images';
import {ArticleData} from '../types/ArticlesData';

export const InitialArticlesList: ArticleData[] = [
  {
    image: Images.longsleeve,
    code: 'CG0934',
    color: 'White',
    size: 'XS',
    title: 'Longsleeve Women X',
    id: 1,
  },
  {
    image: Images.longsleeve,
    code: 'AC8435',
    color: 'White',
    size: 'S',
    title: 'Longsleeve Women Y',
    id: 2,
  },
  {
    image: Images.longsleeve,
    code: 'CG0935',
    color: 'White',
    size: 'XL',
    title: 'Longsleeve Women Z',
    id: 3,
  },
  {
    image: Images.longsleeve,
    code: 'CG0936',
    color: 'White',
    size: 'XL',
    title: 'Longsleeve Women Z',
    id: 4,
  },
  {
    image: Images.longsleeve,
    code: 'CG0937',
    color: 'White',
    size: 'XL',
    title: 'Longsleeve Women Z',
    id: 5,
  },
  {
    image: Images.longsleeve,
    code: 'CG0938',
    color: 'White',
    size: 'XL',
    title: 'Longsleeve Women Z',
    id: 6,
  },
  {
    image: Images.longsleeve,
    code: 'CG0939',
    color: 'White',
    size: 'XL',
    title: 'Longsleeve Women Z',
    id: 7,
  },
  {
    image: Images.longsleeve,
    code: 'CG0940',
    color: 'White',
    size: 'XL',
    title: 'Longsleeve Women Z',
    id: 8,
  },
  {
    image: Images.longsleeve,
    code: 'CG0941',
    color: 'White',
    size: 'XL',
    title: 'Longsleeve Women Z',
    id: 9,
  },
  {
    image: Images.longsleeve,
    code: 'CG0942',
    color: 'White',
    size: 'XL',
    title: 'Longsleeve Women Z',
    id: 10,
  },
];
